version: "3.9"

services:
  backend:
    build:
      context: ./Backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./Frontend/gps-app-vite
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "3000:5173"
    volumes:
      - ./Frontend/gps-app-vite:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true